version: "3.9"
services:
  db:
    container_name: db 
    image: "mysql:8.0"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/V001_create_database.sql:/docker-entrypoint-initdb.d/V001_create_database.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      retries: 100

  laravel:
    container_name: app
    build: 
      context: ./
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:sqLes8qQ+GBmHMFG8ypM2JimEnFXCuXIYMBMONLN/zY=
      APP_DEBUG: "true"
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: local
      DB_USERNAME: root
      DB_PASSWORD: password
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
      LC_ALL: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
    ports:
      - 80:80
      - 443:443
    depends_on:
      db:
        condition: service_healthy